# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    default_locale: cs

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    csrf_protection:
        enabled: true
        check_header: true

    #esi: true
    #fragments: true

    serializer:
        enabled: true
        name_converter: ~

    rate_limiter:
        dashboard_toggle:
            policy: fixed_window
            limit: 10
            interval: '1 minute'
        dashboard_seed:
            policy: fixed_window
            limit: 5
            interval: '1 minute'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
